name: vehicle_tracker
description: Vehicle Service & Maintenance Tracker App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^18.0.1
  fl_chart: ^0.70.2
  intl: ^0.20.2
  uuid: ^4.5.1
  path_provider: ^2.1.5
  timezone: ^0.10.0
  flutter_timezone: ^3.0.1
  firebase_core: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
